language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
  - pip install codecov
# command to run tests
script:
  - cd galaxy_dive; pytest --runslow
after_success:
  - codecov
